#!/usr/bin/env ruby

require 'optparse'
require 'wca_i18n'

def main
  verbose = false
  OptionParser.new do |opts|
    opts.banner = "Usage: #{__FILE__} [options] <base_translation_file> <translation_files>"
    opts.on("-v", "--verbose", "Run verbosely") do |v|
      verbose = v
    end
  end.parse!

  base_translation_file = ARGV.shift
  throw "Please pass a base_translation_file" unless base_translation_file
  throw "base_translation_file not found: #{base_translation_file}" unless File.exist?(base_translation_file)

  translation_files = ARGV
  throw "Please pass a list of translation_files" unless translation_files

  base_translation = load_translation(base_translation_file)
  translations = translation_files.map { |f| load_translation(f) }.reject { |t| t.locale == base_translation.locale }

  compare_base_with_translations(base_translation, translations.sort_by!(&:locale), verbose)
end

def load_translation(filename)
  locale = File.basename(filename, ".*")
  WcaI18n::Translation.new(locale, File.read(filename))
end

def compare_base_with_translations(base_translation, translations, verbose)
  translations.each do |translation|
    diff = translation.compare_to(base_translation)
    puts "#{translation.locale}:#{indent(format_diff(diff, verbose), 1)}"
  end
end

def format_diff(diff, verbose=false)
  types = [:missing, :outdated, :unused]

  pretty_counts = types.map do |type|
    contexts = diff[type]
    pretty = "#{contexts.length} #{type.to_s}"
    pretty += ":\n" + indent(format_contexts(contexts), 1) if verbose
    pretty
  end

  if verbose
    "\n" + pretty_counts.join("\n")
  else
    total = diff.values.map(&:length).sum
    "#{total} total = #{pretty_counts.join(" + ")}"
  end
end

def format_contexts(contexts)
  contexts.map { |context| context.join(" > ") }.join("\n")
end

def indent(str, level)
  str.split("\n").map { |line| "\t"*level + line }.join("\n")
end

main
